version: '3'
services:
  app-stage:
    image: "gcr.io/datacenter-tecnologia-296718/simuladormission_aden_org_stage:$BUILD_TAG"
    ports:
      - "8090:80"
    restart: unless-stopped
    container_name: simuladormission_aden_org_stage
